# Docker compose to test for the deployment image,
# Must be composed with the main docker-compose.yml file

# Right now this is only used to test the deployment image,
# Not (yet) to develop using docker

services:
  explorer:
    build:
      context: .
      dockerfile: Dockerfile
