name: Container Image Deployment CI

on:
  push:
    branches:
      - main
      - deploy/*
    # NO Production deployement yet
    #tags:
    #  - v*.*.*

# Note on secrets used for connection
# They are configured as environment secrets
# HOST is the internal ip of VM containing docker
# PROXY_HOST is the host of VMs
# USERNAME is the user used for operations
# SSH_PRIVATE_KEY is the private key (shared between VM and host)

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    if: github.repository == 'openfoodfacts/openfoodfacts-explorer'
    strategy:
      matrix:
        env:
          - ${{ startsWith(github.ref, 'refs/tags/v') && 'off-explorer-org' || 'off-explorer-net' }}
    environment: ${{ matrix.env }}
    concurrency: ${{ matrix.env }}
    steps:
      - name: Set common variables
        run: |
          echo "SSH_USERNAME=off" >> $GITHUB_ENV
      - name: Set various variable for staging (net) deployment
        if: matrix.env == 'off-explorer-net'
        run: |
          echo "SSH_PROXY_HOST=ovh1.openfoodfacts.org" >> $GITHUB_ENV
          echo "SSH_HOST=10.1.0.200" >> $GITHUB_ENV
          # application parameters
          echo "PUBLIC_FOLKSONOMY_API_URL=https://api.folksonomy.openfoodfacts.net" >> $GITHUB_ENV
          echo "PUBLIC_OFF_BASE_URL=https://world.openfoodfacts.net" >> $GITHUB_ENV
          echo "PUBLIC_SEARCH_BASE_URL=https://search.openfoodfacts.net" >> $GITHUB_ENV
          echo "PUBLIC_AUTH_BASE_URL=https://auth.openfoodfacts.net" >> $GITHUB_ENV
          echo "PUBLIC_AUTH_PKCE_ID=explorer" >> $GITHUB_ENV
          echo "PUBLIC_KEYCLOAK_REALM=openfoodfacts" >> $GITHUB_ENV
          echo "PUBLIC_PRICES_API_URL=https://prices.openfoodfacts.net" >> $GITHUB_ENV
          echo "PUBLIC_ROBOTOFF_URL=https://robotoff.openfoodfacts.net" >> $GITHUB_ENV
          echo "PUBLIC_IMAGES_URL=https://images.openfoodfacts.net" >> $GITHUB_ENV
          echo "PUBLIC_NUTRIPATROL_URL=https://nutripatrol.openfoodfacts.net" >> $GITHUB_ENV
      - name: Set various variable for production deployment
        if: matrix.env == 'off-explorer-org'
        run: |
          echo "NO PRODUCTION DEPLOYMENT YET" && exit 1
      - name: Wait for search service image container build workflow
        uses: tomchv/wait-my-workflow@15c168cfa0cf8d5234974e0047908173d3ab39a1 # v1.1.0
        id: wait-build-service-image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Build and push Explorer Docker image'
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 10
          timeoutSeconds: 600 # 10m

      - name: Do something if build isn't launch
        if: steps.wait-build-service-image.outputs.conclusion == 'does not exist'
        run: echo job does not exist && true

      - name: Do something if build fail
        if: steps.wait-build-service-image.outputs.conclusion == 'failure'
        run: echo fail && false # fail if build fail

      - name: Do something if build timeout
        if: steps.wait-build-service-image.outputs.conclusion == 'timed_out'
        run: echo Timeout && false # fail if build time out

      - name: Checkout git repository
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            # Clone Git repository if not already there
            [ ! -d '${{ matrix.env }}' ] && git clone --depth 1 https://github.com/${{ github.repository }} ${{ matrix.env }} --no-single-branch 2>&1

            # Go to repository directory
            cd ${{ matrix.env }}

            # Fetch newest commits (in case it wasn't freshly cloned)
            git fetch --depth 1

            # Checkout current commit SHA
            git checkout -qf ${{ github.sha }}

      - name: Set environment variables
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            # Go to repository directory
            cd ${{ matrix.env }}

            # init .env
            echo "# Env file generated by container-deploy action"> .env
            echo "DOCKER_IMAGE_TAG=sha-${{ github.sha }}"
            echo >> .env <<EOF=====
            DOCKER_IMAGE_NAME=openfoodfacts/explorer
            DOCKER_EXPLORER_EXPOSE=:3000
            COMPOSE_PATH_SEPARATOR=;
            COMPOSE_FILE=docker-compose.yml;docker/dev.yml
            RESTART_POLICY=no
            EOF=====
            # Set App variables
            echo "PUBLIC_FOLKSONOMY_API_URL=${{ env.PUBLIC_FOLKSONOMY_API_URL }}" >> $GITHUB_ENV
            echo "PUBLIC_OFF_BASE_URL=${{ env.PUBLIC_OFF_BASE_URL }}" >> $GITHUB_ENV
            echo "PUBLIC_SEARCH_BASE_URL=${{ env.PUBLIC_SEARCH_BASE_URL }}" >> $GITHUB_ENV
            echo "PUBLIC_AUTH_BASE_URL=${{ env.PUBLIC_AUTH_BASE_URL }}" >> $GITHUB_ENV
            echo "PUBLIC_AUTH_PKCE_ID=${{ env.PUBLIC_AUTH_PKCE_ID }}" >> $GITHUB_ENV
            echo "PUBLIC_KEYCLOAK_REALM=${{ env.PUBLIC_KEYCLOAK_REALM }}" >> $GITHUB_ENV
            echo "PUBLIC_PRICES_API_URL=${{ env.PUBLIC_PRICES_API_URL }}" >> $GITHUB_ENV
            echo "PUBLIC_ROBOTOFF_URL=${{ env.PUBLIC_ROBOTOFF_URL }}" >> $GITHUB_ENV
            echo "PUBLIC_IMAGES_URL=${{ env.PUBLIC_IMAGES_URL }}" >> $GITHUB_ENV
            echo "PUBLIC_NUTRIPATROL_URL=${{ env.PUBLIC_NUTRIPATROL_URL }}" >> $GITHUB_ENV

      - name: Re-start services
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            cd ${{ matrix.env }}
            docker compose down
            docker compose up -d --wait

      - name: Check services are up
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        if: ${{ always() }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            cd ${{ matrix.env }}
            [[ -z $(docker compose  ps -q --status exited --status dead --status removing --status paused) ]] || exit 1

      - name: Cleanup obsolete Docker objects
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        if: ${{ always() }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            cd ${{ matrix.env }}
            docker system prune -af
